---
- hosts: local
  name: "Guest OS (Ansible on guest)"
  vars_files:
    - ../settings.yml

  roles:
    - role: yum
    - role: common
    # - role: jenkins
    - role: apache
    - role: mysql
    - role: memcached
    - role: php
