---

- name: Get jenkins repo
  get_url: url="http://pkg.jenkins-ci.org/redhat/jenkins.repo" dest=/etc/yum.repos.d/jenkins.repo
  sudo: true

- name: Set jenkins repo
  command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
  sudo: true

- name: Install dependencies
  yum: name=java-1.7.0-openjdk state=latest
  sudo: true

- name: Install jenkins
  yum: name=jenkins state=latest
  sudo: true

- name: Start jenkins service
  service: name=jenkins state=started
  sudo: true
